version: '3.8'

services:
  portal:
    image: yasmany/portal:latest
    environment:
      GATEWAY_API_URL: ${GATEWAY_API_URL}
      GATEWAY_AUTH0_AUDIENCE: ${GATEWAY_AUTH0_AUDIENCE}
      NEXT_PUBLIC_SIGNALING_SERVER_URL: ${NEXT_PUBLIC_SIGNALING_SERVER_URL}
    depends_on:
      - gateway

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  omnisdb:
    image: 'mongo:6.0.2-focal'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - omnisdb-data:/data/db

  gateway:
    image: yasmany/gateway:latest
    environment:
      RABBITMQ_DSN: ${RABBITMQ_DSN}
      AUTH0_AUDIENCE: ${GATEWAY_AUTH0_AUDIENCE}
      AUTH0_ISSUER_URL: ${GATEWAY_AUTH0_ISSUER_URL}
    depends_on:
      - rabbitmq

  recruitment:
    image: yasmany/recruitment:latest
    depends_on:
      - rabbitmq
      - omnisdb
    environment:
      MONGO_DSN: ${MONGO_DSN}
      RABBITMQ_DSN: ${RABBITMQ_DSN}

volumes:
  omnisdb-data:
