version: '3.8'

services:
  portal:
    env_file:
      - .env.prod
    build:
      context: ./portal
      target: production
    environment:
      NODE_ENV: production

  gateway:
    env_file:
      - .env.prod
    build:
      context: ./gateway
      target: production
    environment:
      NODE_ENV: production

  recruitment:
    env_file:
      - .env.prod
    build:
      context: ./recruitment
      target: production
    environment:
      NODE_ENV: production

  meetings:
    env_file:
      - .env.prod
    build:
      context: ./meetings
      target: production
    environment:
      NODE_ENV: production

  signal:
    env_file:
      - .env.prod
    build:
      context: ./signal
      target: production
    environment:
      NODE_ENV: production
