version: '3.8'

services:
  portal:
    env_file:
      - .env.prod
    restart: always
    ports:
      - ${OMNIS_PORT}:3000
    environment:
      NODE_ENV: production
    stdin_open: true

  rabbitmq:
    env_file:
      - .env.prod

  omnisdb:
    env_file:
      - .env.prod

  gateway:
    env_file:
      - .env.prod
    restart: always
    ports:
      - ${GATEWAY_PORT}:3000
    environment:
      NODE_ENV: production
    stdin_open: true

  recruitment:
    env_file:
      - .env.prod
    restart: always
    environment:
      NODE_ENV: production
    stdin_open: true

  meetings:
    env_file:
      - .env.prod
    restart: always
    environment:
      NODE_ENV: production
    stdin_open: true

  signal:
    env_file:
      - .env.prod
    ports:
      - ${SIGNAL_PORT}:3000
    restart: always
    environment:
      NODE_ENV: production
    stdin_open: true

  postgres:
    env_file:
      - .env.prod

  keycloak:
    env_file:
      - .env.prod
