version: '3.8'

services:
  portal:
    env_file:
      - .prod.env
    ports:
      - ${PORTAL_PORT}:3000
    environment:
      NODE_ENV: production

  gateway:
    env_file:
      - .prod.env
    ports:
      - ${GATEWAY_PORT}:3000
    environment:
      NODE_ENV: production

  recruitment:
    env_file:
      - .prod.env
    environment:
      NODE_ENV: production
