name: Clone Repo via SSH to Remote Machine and Run Docker Compose

on:
  push:
    branches:
      - main

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Remote Machine via SSH and Create Folder with Current Time
        uses: appleboy/ssh-action@v0.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            folder_name=$(date +%Y-%m-%d-%H-%M-%S)
            mkdir $folder_name

      - name: Clone Repository via SSH
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          repository: ssh://${{ secrets.GIT_SSH_USERNAME }}@${{ secrets.GIT_SSH_HOST }}:${{ secrets.GIT_SSH_PORT }}/${{ secrets.REPO_NAME }}
          path: ./$folder_name/${{ secrets.REPO_NAME }}

      - name: Run Docker Compose
        run: |
          cd ./$folder_name/${{ secrets.REPO_NAME }}
          docker-compose up -d
