name: Deploy Omnis
on: [workflow_dispatch]

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Save Folder Name to Variable
      run: echo "::set-output name=folder_name::$(date +'%Y-%m-%d')"
      id: save-folder-name
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH into remote machine and execute command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo su
          mkdir code
          cd code
          mkdir ${{ steps.save-folder-name.outputs.folder_name }}
          cd ${{ steps.save-folder-name.outputs.folder_name }}
          git clone git@github.com:yasmanymd/omnis.git
          ls
