name: Clone Repo via SSH to Remote Machine and Run Docker Compose

on: [workflow_dispatch]

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Remote Machine via SSH and Create Folder with Current Time
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            folder_name=$(date +%Y-%m-%d-%H-%M-%S)
            mkdir $folder_name

      - name: Clone Repository via SSH
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: git@github.com:yasmanymd/omnis.git
          path: ./$folder_name/omnis

      - name: Run Docker Compose
        run: |
          cd ./$folder_name/${{ secrets.REPO_NAME }}
          docker-compose up -d
